# Generated by Django 4.0.3 on 2022-03-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_note_note_note_title_note_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='completed_flag',
            field=models.BooleanField(default=False),
        ),
    ]
