# Generated by Django 4.0.3 on 2022-03-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='priority_type',
            field=models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='low', max_length=50),
        ),
    ]
