# Generated by Django 4.0.3 on 2022-03-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_priority_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['created']},
        ),
    ]
